const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto'),os=require('os');
const sessions=new Map(); let writeQueue=Promise.resolve();
const DATA=process.env.TELEC_DATA_DIR||path.join(__dirname,'data'),BACK=process.env.TELEC_BACKUP_DIR||path.join(__dirname,'backups'); fs.mkdirSync(DATA,{recursive:true});fs.mkdirSync(BACK,{recursive:true}); const DB=path.join(DATA,'database.json');
const hash=(p,s=crypto.randomBytes(16).toString('hex'))=>({salt:s,hash:crypto.pbkdf2Sync(p,s,120000,32,'sha256').toString('hex')});
function seed(){const h=hash('Telec@2026');return{version:3,users:[{id:'u1',name:'Administrator',username:'admin',role:'admin',active:true,...h,createdAt:new Date().toISOString()}],events:[],audit:[],settings:{company:'TELEC Group',geminiApiKey:'',appsScriptUrl:'https://script.google.com/macros/s/AKfycbxLiidZz0j7e65Pn8m-FavIvE_7p-vn7i4-CSrgO5cYm2YiYP0JmES7AEY1OMHLYuxuEA/exec',autoSheetSync:true}}}
function read(){if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify(seed(),null,2));const d=JSON.parse(fs.readFileSync(DB,'utf8'));d.settings=d.settings||{};d.settings.company=d.settings.company||'TELEC Group';d.settings.geminiApiKey=d.settings.geminiApiKey||'';d.settings.appsScriptUrl=d.settings.appsScriptUrl||'https://script.google.com/macros/s/AKfycbxLiidZz0j7e65Pn8m-FavIvE_7p-vn7i4-CSrgO5cYm2YiYP0JmES7AEY1OMHLYuxuEA/exec';d.settings.autoSheetSync=d.settings.autoSheetSync!==false;return d}
function save(db){writeQueue=writeQueue.then(()=>{const t=DB+'.tmp';fs.writeFileSync(t,JSON.stringify(db,null,2));fs.renameSync(t,DB)});return writeQueue}
function backup(db){const d=new Date().toISOString().replace(/[:.]/g,'-');fs.writeFileSync(path.join(BACK,`backup-${d}.json`),JSON.stringify(db,null,2));const f=fs.readdirSync(BACK).sort();while(f.length>30)fs.unlinkSync(path.join(BACK,f.shift()))}
const id=p=>p+crypto.randomBytes(8).toString('hex');
function auth(req,res,next){const s=sessions.get((req.headers.authorization||'').replace('Bearer ',''));if(!s)return res.status(401).json({error:'Session expired. Please login again.'});req.user=s;next()}
const admin=(req,res,next)=>req.user.role==='admin'?next():res.status(403).json({error:'Administrator access required.'});
function audit(db,u,action,detail){db.audit.unshift({id:id('a'),at:new Date().toISOString(),user:u.name,username:u.username,action,detail});db.audit=db.audit.slice(0,2000)}
function clean(x){return{eventDate:String(x.eventDate||''),eventTime:String(x.eventTime||''),familyPersonName:String(x.familyPersonName||'').trim(),eventType:String(x.eventType||'').trim(),day:String(x.day||'').trim(),venueLocation:String(x.venueLocation||'').trim(),city:String(x.city||'').trim(),googleMapsLink:String(x.googleMapsLink||'').trim(),details:String(x.details||'').trim(),status:String(x.status||'Pending'),posterName:String(x.posterName||'').trim()}}
function network(){const port=Number(process.env.PORT||4310);const a=[];for(const g of Object.values(os.networkInterfaces()))for(const n of g||[])if(n.family==='IPv4'&&!n.internal)a.push(`http://${n.address}:${port}`);return a}
const GEMINI_MODELS=['gemini-3.6-flash','gemini-3.5-flash','gemini-3.5-flash-lite'];
function isModelAvailabilityError(message){return /no longer available|not found|not supported|is not available|unsupported model|model.*unavailable/i.test(String(message||''))}
async function geminiGenerate(key,body){
 if(!key)throw new Error('Gemini API key is not configured. Admin can add it in Settings.');
 let lastError='Gemini request failed.';
 for(const model of GEMINI_MODELS){
  const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  const d=await r.json().catch(()=>({}));
  if(r.ok)return{data:d,model};
  lastError=d?.error?.message||`Gemini request failed (${r.status}).`;
  if(!isModelAvailabilityError(lastError))throw new Error(lastError);
 }
 throw new Error(lastError);
}
async function parsePoster(dataUrl,key){if(!key)throw new Error('Gemini API key is not configured. Admin can add it in Settings.');const m=dataUrl.match(/^data:(.*?);base64,(.*)$/);if(!m)throw new Error('Invalid poster image.');const prompt=`Read this event invitation poster carefully. Return ONLY valid JSON with these exact keys: eventDate (YYYY-MM-DD), eventTime (HH:MM 24-hour), familyPersonName, eventType, day, venueLocation, city, googleMapsLink, details. familyPersonName means invited person, host family, or main person shown. details should include organiser, speakers, RSVP, contact, dress code and other useful text. Do not invent missing facts; use empty string.`;
 const result=await geminiGenerate(key,{contents:[{parts:[{text:prompt},{inline_data:{mime_type:m[1],data:m[2]}}]}],generationConfig:{responseMimeType:'application/json'}});const txt=result.data?.candidates?.[0]?.content?.parts?.[0]?.text||'{}';try{return JSON.parse(txt)}catch{throw new Error('Gemini read the poster but returned invalid JSON. Please try again.')}}

async function sheetCall(url,payload){
 if(!url)throw new Error('Google Apps Script URL is not configured.');
 const r=await fetch(url,payload?{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),redirect:'follow'}:{redirect:'follow'});
 const text=await r.text();let d;try{d=JSON.parse(text)}catch{throw new Error('Google Sheet returned an invalid response. Check Web App access is set to Anyone.');}
 if(!r.ok||d.success===false)throw new Error(d.message||'Google Sheet connection failed.');return d;
}
async function syncEventToSheet(event,url){return sheetCall(url,{action:'addEvent',event:{eventDate:event.eventDate,eventTime:event.eventTime,familyPersonName:event.familyPersonName,eventType:event.eventType,day:event.day,venueLocation:event.venueLocation,city:event.city,googleMapsLink:event.googleMapsLink,additionalDetails:event.details,status:event.status}})}
async function testGemini(key){if(!key)throw new Error('Gemini API key is not configured.');const result=await geminiGenerate(key,{contents:[{parts:[{text:'Reply with only OK'}]}],generationConfig:{maxOutputTokens:10}});return result.model}

function csv(events){const h=['Event Date','Event Time','Family / Person Name','Event Type','Day','Venue / Location','City','Google Maps Link','Details','Status'];const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return '\ufeff'+[h,...events.sort((a,b)=>(a.eventDate+a.eventTime).localeCompare(b.eventDate+b.eventTime)).map(e=>[e.eventDate,e.eventTime,e.familyPersonName,e.eventType,e.day,e.venueLocation,e.city,e.googleMapsLink,e.details,e.status])].map(r=>r.map(q).join(',')).join('\r\n')}
function start(port=Number(process.env.PORT||4310)){const app=express();app.set('trust proxy',1);app.use(express.json({limit:'12mb'}));app.use(express.static(path.join(__dirname,'public')));
app.get('/health',(req,res)=>res.json({ok:true,service:'TELEC Event Manager',version:'2.6.0'}));
app.post('/api/login',(req,res)=>{const db=read(),u=db.users.find(x=>x.username.toLowerCase()===String(req.body.username||'').toLowerCase()&&x.active);if(!u)return res.status(401).json({error:'Invalid username or password.'});const h=hash(String(req.body.password||''),u.salt).hash;if(!crypto.timingSafeEqual(Buffer.from(h),Buffer.from(u.hash)))return res.status(401).json({error:'Invalid username or password.'});const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{id:u.id,name:u.name,username:u.username,role:u.role});audit(db,u,'LOGIN','Successful login');save(db);res.json({token})});
app.get('/api/bootstrap',auth,(req,res)=>{const db=read();res.json({user:req.user,events:db.events,users:req.user.role==='admin'?db.users.map(({hash,salt,...u})=>u):[],audit:req.user.role==='admin'?db.audit.slice(0,200):[],network:network(),settings:req.user.role==='admin'?{geminiConfigured:!!db.settings.geminiApiKey,appsScriptUrl:db.settings.appsScriptUrl||'',sheetConfigured:!!db.settings.appsScriptUrl,autoSheetSync:db.settings.autoSheetSync!==false}:{}})});
app.post('/api/events',auth,async(req,res)=>{const e=clean(req.body);if(!e.eventDate||!e.eventTime||!e.familyPersonName||!e.eventType)return res.status(400).json({error:'Event Date, Event Time, Family / Person Name and Event Type are required.'});const db=read();if(db.events.some(x=>x.eventDate===e.eventDate&&x.eventTime===e.eventTime&&x.familyPersonName.toLowerCase()===e.familyPersonName.toLowerCase()&&x.venueLocation.toLowerCase()===e.venueLocation.toLowerCase()))return res.status(409).json({error:'This event already exists.'});const now=new Date().toISOString(),row={id:id('e'),...e,createdAt:now,updatedAt:now,createdBy:req.user.name,updatedBy:req.user.name,revision:1};db.events.push(row);audit(db,req.user,'EVENT_CREATED',`${e.familyPersonName} - ${e.eventType}`);backup(db);await save(db);let sheetSync={success:false,skipped:true};if(db.settings.autoSheetSync&&db.settings.appsScriptUrl){try{await syncEventToSheet(row,db.settings.appsScriptUrl);sheetSync={success:true}}catch(err){sheetSync={success:false,error:err.message}}}res.json({...row,sheetSync})});
app.put('/api/events/:id',auth,async(req,res)=>{const db=read(),i=db.events.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Event not found.'});if(+req.body.revision!==db.events[i].revision)return res.status(409).json({error:'Another user updated this event. Refresh and try again.'});const e=clean(req.body);db.events[i]={...db.events[i],...e,updatedAt:new Date().toISOString(),updatedBy:req.user.name,revision:db.events[i].revision+1};backup(db);audit(db,req.user,'EVENT_UPDATED',`${e.familyPersonName} - ${e.eventType}`);await save(db);res.json(db.events[i])});
app.delete('/api/events/:id',auth,admin,async(req,res)=>{const db=read(),i=db.events.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Event not found.'});backup(db);const[e]=db.events.splice(i,1);audit(db,req.user,'EVENT_DELETED',e.familyPersonName);await save(db);res.json({ok:true})});
app.post('/api/poster/parse',auth,async(req,res)=>{try{const db=read();const out=await parsePoster(req.body.dataUrl,db.settings.geminiApiKey||process.env.GEMINI_API_KEY);res.json(out)}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/settings',auth,admin,async(req,res)=>{const db=read();if(Object.prototype.hasOwnProperty.call(req.body,'geminiApiKey')&&String(req.body.geminiApiKey||'').trim())db.settings.geminiApiKey=String(req.body.geminiApiKey).trim();if(Object.prototype.hasOwnProperty.call(req.body,'appsScriptUrl'))db.settings.appsScriptUrl=String(req.body.appsScriptUrl||'').trim();if(typeof req.body.autoSheetSync==='boolean')db.settings.autoSheetSync=req.body.autoSheetSync;audit(db,req.user,'SETTINGS_UPDATED','Poster Reader and Google Sheet settings updated');await save(db);res.json({ok:true,geminiConfigured:!!db.settings.geminiApiKey,sheetConfigured:!!db.settings.appsScriptUrl,appsScriptUrl:db.settings.appsScriptUrl,autoSheetSync:db.settings.autoSheetSync!==false})});
app.post('/api/settings/test-gemini',auth,admin,async(req,res)=>{try{const db=read();const model=await testGemini(String(req.body.geminiApiKey||'').trim()||db.settings.geminiApiKey);res.json({ok:true,message:`Gemini connection successful (${model}).`})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/settings/test-sheet',auth,admin,async(req,res)=>{try{const db=read(),url=String(req.body.appsScriptUrl||'').trim()||db.settings.appsScriptUrl;const d=await sheetCall(url);res.json({ok:true,message:d.message||'Google Sheet connection successful.'})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/users',auth,admin,async(req,res)=>{const db=read(),username=String(req.body.username||'').trim();if(!username||!req.body.name||String(req.body.password||'').length<8)return res.status(400).json({error:'Complete all user fields. Password must be at least 8 characters.'});if(db.users.some(x=>x.username.toLowerCase()===username.toLowerCase()))return res.status(409).json({error:'Username already exists.'});const u={id:id('u'),name:String(req.body.name).trim(),username,role:['admin','editor','viewer'].includes(req.body.role)?req.body.role:'viewer',active:true,...hash(req.body.password),createdAt:new Date().toISOString()};db.users.push(u);audit(db,req.user,'USER_CREATED',username);await save(db);const{hash:_,salt:__,...safe}=u;res.json(safe)});
app.patch('/api/users/:id',auth,admin,async(req,res)=>{const db=read(),u=db.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'User not found.'});if(u.id===req.user.id&&req.body.active===false)return res.status(400).json({error:'You cannot disable your own account.'});if(typeof req.body.active==='boolean')u.active=req.body.active;await save(db);res.json({ok:true})});
app.get('/api/export.csv',auth,(req,res)=>{res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename=TELEC_Event_Data.csv');res.send(csv(read().events))});
app.post('/api/backup',auth,admin,(req,res)=>{backup(read());res.json({ok:true})});app.post('/api/logout',auth,(req,res)=>{for(const[k,v]of sessions)if(v===req.user)sessions.delete(k);res.json({ok:true})});
app.use((e,req,res,next)=>{console.error(e);res.status(500).json({error:'Unexpected error. Your saved data was not changed.'})});return app.listen(port,'0.0.0.0',()=>console.log(`TELEC Event Manager running at http://localhost:${port}`))}
module.exports={start};if(require.main===module)start(Number(process.env.PORT||4310));
